Repository Lounol72/ICPocket, pull requests merged in 2025-04, with the labels that each got.

#46 36 attack animations
  assets/Tileset/Map/hall.csv
  data/dataText.csv
  data/dataTrainer.csv
  data/save/Save_1.txt
  include/GameEngine.h
  include/Map.h
  include/Player.h
  include/ThreadManager.h
  src/Events.c
  src/Game.c
  src/GameEngine.c
  src/Map.c
  src/Player.c
  src/RenderICMons.c
  src/ThreadManager.c
  test/test_Map.c
Labels: bug, enhancement

#49 📚 Add function documentation for game initialization, AI movement, an…
  include/Map.h
  include/Player.h
  include/RenderICMons.h
  include/Window.h
  include/structPoke.h
  src/Camera.c
  src/Events.c
  src/GameEngine.c
  src/Images.c
  src/Log.c
  src/Map.c
  src/Player.c
  src/RenderICMons.c
  src/Text.c
  src/ThreadManager.c
  src/Window.c
  src/interDuel.c
  src/mainDuel.c
  src/ministdlib.c
  src/save.c
  src/structPoke.c
  src/trainerAI.c
Labels: bug, documentation

#50 mkdir on save and quit window when lose
  include/Game.h
  include/GameEngine.h
  rapport/.nfs00000000084204ef0000001a
  src/Events.c
  src/Game.c
  src/GameEngine.c
  src/save.c
Labels: bug, enhancement

#51 Test windows build
  .gitattributes
  .github/workflows/windows-build.yml
  ICPocket-windows.zip
  src/duel.c
  src/save.c
Labels: bug
